Update link.py
reflex-dev/reflex pull request #1488
Opened 2023-08-01 02:49 UTC by ckavanagh21

closes #1486

### All Submissions:

- [ x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [ x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [x ] Does your submission pass the tests? 
- [ x] Have you linted your code locally prior to submission?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2023-08-01 03:34 UTC, masenf approved these changes

2023-08-03 19:20 UTC, masenf requested changes

2023-08-03 19:20 UTC, masenf commented on reflex/components/navigation/link.py
>          elif href is None and len(children):
```suggestion
        elif not href and len(children):
```

Changing the condition here to a falsey check will actually fix the issue seen in #1486, where the user supplies `href=""`

2023-08-05 18:53 UTC, danik292 commented
@masenf check it pls

2023-08-05 18:54 UTC, danik292 approved these changes

2023-08-05 19:25 UTC, masenf approved these changes

2023-08-05 19:28 UTC, masenf requested changes
there's still something not quite right, i can look into it next week

```
  File "/home/runner/work/reflex/reflex/reflex-web/pcweb/components/sidebar.py", line 249, in sidebar_leaf
    rx.link(
  File "/home/runner/work/reflex/reflex/reflex/components/navigation/link.py", line 51, in create
    raise ValueError("Invalid href passed in Link. Expected a 'str' for href.")
ValueError: Invalid href passed in Link. Expected a 'str' for href.
```

https://github.com/reflex-dev/reflex-web/blob/455e9b29587ff830081fcf9c78c18522f9034c42/pcweb/components/sidebar.py#L249-L252

It looks like `href` can also be a `Var`, not just a str.

you might try changing line 50 to be something like `if href and not isinstance(href, (str, Var)):`

2023-08-21 22:16 UTC, closed without merging