updated CONTRIBUTING.md, just made it more fun
reflex-dev/reflex pull request #2020
Opened 2023-10-23 14:10 UTC by 0Armaan025

### All Submissions:

- [✔️ ] Have you followed the guidelines stated in the [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [✔️] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired change?

### Type of change

Please delete options that are not relevant.
- [✔️ ] This change requires a documentation update

INFO:

Hey there!
First, if you are reading this, you are amazing!

I am Armaan and actively taking part in Hacktoberfest and HackSquad, I came across this amazing repo to contribute and found out "CONTRIBUTING.md" as a bit plain ( my opinion ), and thought why not contribute to make it more fun and that's what I did!

There have been no code changes, just the docs update as I thought it was not too engaging, nothing else!

If the maintainers/repo owners want to keep it the same as before, I'm sorry for this unnecessary PR and taking up your precious time, you can definitely have a look at it, if you liked it, you can merge it otherwise, this PR can be closed and I apologise if there are any mistakes.

Additional INFO:  Starred✔️⭐

Thanks and regards,
Armaan.

2023-10-23 17:17 UTC, masenf approved these changes
Cool, thanks for contributing

2023-10-23 18:53 UTC, Lendemor requested changes
A few changes are needed, but I love it, thanks.

2023-10-23 18:53 UTC, Lendemor commented on CONTRIBUTING.md
> +Within the 'test' directory of Reflex, you can add to an existing test file or create a new test Python file if it doesn't fit the current layout.
```suggestion
Within the 'tests' directory of Reflex, you can add to an existing test file or create a new test Python file if it doesn't fit the current layout.
```

2023-10-23 18:53 UTC, Lendemor commented on CONTRIBUTING.md
>  ## 🧪 Testing and QA
I don't think we need the `## Testing and QA` title twice.

2023-10-23 18:53 UTC, Lendemor commented on CONTRIBUTING.md
> +Now, Init and Run:
I think this part was repeated wrongly, should probably be removed as it already appear on line 33.

2024-04-02 16:37 UTC, masenf commented
Please resolve conflicts and reopen if you still wish to contribute.

2024-04-02 16:37 UTC, closed without merging