Apply new pyi script
reflex-dev/reflex pull request #2041
Opened 2023-10-26 18:52 UTC by Lendemor

For all components except plotly, need to resolve resolution conflict.

2023-10-26 19:11 UTC, Alek99 commented
I'm not so comfortable changing all the pyi files this close to calhacks, lets just generate this for the new data editor

2023-10-26 19:14 UTC, Alek99 requested changes
I'm not comfortable with this large of a pr so close to the release and calhacks, lets just add the new pyi for the data editor and keep the old pyi for the other files

2023-10-26 19:30 UTC, masenf requested changes
Looks good, but looks big. I can understand the hesitation to bring this in this close to calhacks.

One other fixup is needed from my previous PR:

2023-10-26 19:30 UTC, masenf commented on reflex/components/base/body.pyi
> +    ...
oops, these shouldn't be here if the class is not empty...we should move these lines (https://github.com/reflex-dev/reflex/blob/9e5a47b52d51b7a60608355515de82a57ee2ba69/scripts/pyi_generator.py#L449-L451) to the end of that `visit_ClassDef` function to ensure we dont add the ellipsis when we will generate a function.

2023-10-26 21:09 UTC, Lendemor commented
> I'm not comfortable with this large of a pr so close to the release and calhacks, lets just add the new pyi for the data editor and keep the old pyi for the other files

Then I'll add it on the datatable PR and we can merge this one after the release.

2023-11-16 18:23 UTC, masenf approved these changes
nice

2023-11-16 18:27 UTC, merged