Add 'orientation' Property to Reflex Stepper Components
reflex-dev/reflex pull request #2089
Opened 2023-10-31 13:25 UTC by shu-qian

### Pull Request Description
This Pull Request addresses issue #2088 and add 'orientation' Property to  Stepper , This enhancement provides more flexibility in configuring the layout of the stepper components.

### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

2023-10-31 16:58 UTC, masenf approved these changes

2023-10-31 17:16 UTC, masenf requested changes

2023-10-31 17:16 UTC, masenf commented on reflex/components/navigation/stepper.py
> +    orientation: Var[Literal["vertical", "horizontal"]]
Need to import `Literal`

2023-11-01 02:00 UTC, shu-qian commented
Sorry I have imported Literal now

2023-11-01 15:30 UTC, masenf commented on reflex/components/navigation/stepper.py
> +from typing import Literal
```suggestion
from typing import List, Literal, Optional, Tuple
```

2023-11-01 18:51 UTC, masenf approved these changes

2023-11-01 18:51 UTC, merged