Add high-level API for accordion
reflex-dev/reflex pull request #2285
Opened 2023-12-13 01:46 UTC by picklelo

* Add high level Accordion API
* Handle `apply_theme` within `rx.foreach`

Test code:

```python
"""Welcome to Reflex! This file outlines the steps to create a basic app."""
from rxconfig import config

import reflex as rx
import reflex.components.radix.themes as rdxt
import reflex.components.radix.primitives as rdxp

class State(rx.State):
    """The app state."""

    items: list[tuple[str, str]] = [
        ("Is it accessible?", "Yes. It's built with accessibility in mind."),
        ("Is it unstyled?", "Yes. It's unstyled by default, giving you freedom over the look and feel."),
        ("Is it finished?", "It's still in beta, but it's ready to use in production."),
    ]

def index() -> rx.Component:
    return rdxt.theme(
        rdxt.container(
            rdxt.flex(
                rdxp.accordion(
                    rdxp.accordion_item("Is it accessible?", rdxt.button("Test button"), disabled=True, font_size="3em"),
                    rdxp.accordion_item("Is it unstyled?", "Yes. It's unstyled by default, giving you freedom over the look and feel."),
                    rdxp.accordion_item("Is it finished?", "It's still in beta, but it's ready to use in production."),
                    type="single",
                    collapsible=True,
                    width="300px",
                ),
                rdxp.accordion(
                    rx.foreach(
                        State.items,
                        lambda item, i: rdxp.accordion_item(item[0], item[1], value=f"item-{i}"),
                    ),
                    type="single",
                    collapsible=True,
                    width="300px",
                ),
            ),
            padding_y="5em",
            font_size="2em",
            text_align="center",
        )
    )

# Add state and page to the app.
app = rx.App(
    theme=rdxt.theme(
        appearance="dark", has_background=True, radius="none", accent_color="crimson"
    ),
)

app.add_page(index)
app.compile()
```

2023-12-13 03:31 UTC, Alek99 commented
Api looks nice but how would one use the low level accordion items when we override it here with the high level accordion_item

2023-12-13 17:26 UTC, Lendemor requested changes
Need an example where the primitives render properly even if we are not using any theme.

2023-12-14 01:16 UTC, picklelo commented
> Api looks nice! How would one use the low-level accordion items when we override them here with the high-level accordion_item
> 
> I guess the broader question is will the low and high level share the same namespace and how to accommodate this if so

Discussed offline - but we're thinking that we shouldn't let the user combine high/low level APIs. Not sure if we should detect this (maybe we can through the `valid_children`) but we can at least document that they shouldn't be mixed.

The high level will be in the `rx.` namespace and the low-level will be in the `rx.radix` namespace so we can have a general rule of thumb to not mix components from different namespaces.

2023-12-19 01:21 UTC, Alek99 approved these changes

2023-12-19 01:21 UTC, merged