Refactor chakra components into separate folder
reflex-dev/reflex pull request #2315
Opened 2023-12-20 01:19 UTC by picklelo

This change moves most of the core components into the `reflex/components/chakra` namespace, in order to prepare for the switch to the Radix components.

All imports for end-users should work exactly as is, this is just an internal restructuring.

2023-12-20 13:49 UTC, Lendemor requested changes
A few changes needed but I'm glad this PR is finally here 😄

2023-12-20 13:49 UTC, Lendemor commented on reflex/components/chakra/forms/debounce.py
Debounce is not chakra specific, it can probably go to `core` or it's own folder.

2023-12-20 13:49 UTC, Lendemor commented on reflex/components/chakra/forms/password.py
since `Password` doesn't actually exist in Chakra, this should probably become a high level component only, that specialize an input with `type="password"`

2023-12-20 13:49 UTC, Lendemor commented on reflex/components/chakra/layout/fragment.pyi
Fragment moved to core, this pyi should be removed.

2023-12-20 13:49 UTC, Lendemor commented on reflex/components/chakra/navigation/nextlink.pyi
should be removed

2023-12-20 13:49 UTC, Lendemor commented on reflex/components/chakra/overlay/banner.pyi
should be removed

2023-12-20 13:49 UTC, Lendemor commented on reflex/components/radix/themes/components/textarea.pyi
> +from reflex.components.chakra.forms.debounce import DebounceInput
fix those imports when debounce is moved to `core`

2023-12-20 20:33 UTC, masenf commented on requirements.txt
why is this here? and why is it considered a binary file?

2023-12-20 20:38 UTC, picklelo commented on reflex/components/chakra/forms/debounce.py
Moving this

2023-12-20 20:38 UTC, picklelo commented on reflex/components/chakra/forms/password.py
Agreed, I think these ones are tied to the Chakra Input component, maybe we can leave it for now and abstract it later.

2023-12-20 20:38 UTC, picklelo commented on requirements.txt
Removed and added go gitignore (I think it comes from running the unit tests for me, we should probably see why)

2023-12-20 22:33 UTC, masenf submitted a review, later dismissed

2023-12-20 22:33 UTC, masenf commented on reflex/components/chakra/forms/multiselect.py
why no `pyi` file for this component?

2023-12-20 23:42 UTC, picklelo commented on reflex/components/chakra/forms/multiselect.py
I'm not sure, I ran the generator

2023-12-21 12:04 UTC, Lendemor approved these changes

2023-12-21 12:44 UTC, Lendemor commented on reflex/components/chakra/forms/multiselect.py
multiselect.py is black-listed in the generator, probably a remnant of when it was broken ?

2023-12-21 17:51 UTC, picklelo commented on reflex/components/chakra/forms/multiselect.py
We can bring it back now I suppose

2023-12-21 17:52 UTC, merged