Chakra Layout Switch Import
reflex-dev/reflex pull request #2405
Opened 2024-01-17 18:30 UTC by Alek99

Continue using chakra layout components as base layout, radix layout will override for duplicates

https://www.npmjs.com/package/@chakra-ui/layout?activeTab=readme

2024-01-18 01:11 UTC, masenf approved these changes
Initial check looks good

2024-01-18 21:23 UTC, Alek99 commented
> Initial check looks good

Do you see a problem with how my change will affect the failed unit tests switching the level of the chakra provider.

2024-01-18 22:19 UTC, masenf requested changes
the app wrap ordering become order dependent since the test uses priority `50` for the `Text` App Wrap and `ChakraColorModeProvider` is also at priority `50`.

I would probably change the test to use `return {(45, "Text"): Text.create()}` on line 1254, that way the sorting is deterministic instead of depending on the order the components were added to the tree.

2024-01-19 00:30 UTC, masenf submitted a review, later dismissed

2024-01-25 17:58 UTC, picklelo approved these changes

2024-01-25 18:22 UTC, merged