add lucide icons as a candidate for core icon library
reflex-dev/reflex pull request #2444
Opened 2024-01-24 16:24 UTC by Lendemor

`size`, `strokeWidth` and `color` can be customized like in the following example:

```python
import reflex as rx

rx.lucide.icon(tag="moon", size=24, strokeWidth="1"),
rx.lucide.icon(tag="moon", size=48, strokeWidth="2"),
rx.lucide.icon(tag="moon", size=24, strokeWidth="2", color="red"),
rx.lucide.icon(tag="moon", size=48, strokeWidth="2", color="blue"),
```

<img width="250" alt="image" src="https://github.com/reflex-dev/reflex/assets/4015177/21ee8c2d-cfd6-41e2-ba94-1365e809c8d9">

2024-01-24 17:47 UTC, Alek99 requested changes
### Comments from discord 
he only comment I have with this is that if they are using the theme provider I would like this to default to using it so it can look good in a button like so https://www.radix-ui.com/themes/docs/components/button
We may need to make a method that can check if a theme is being used
We can also get rid of radix icons as we only need one icon lib

2024-01-24 17:47 UTC, Alek99 commented on reflex/components/lucide/icon.py
Hard  pin version here

2024-01-25 21:47 UTC, Alek99 commented on reflex/components/lucide/icon.py
This is the only one needing to be addressed now

2024-01-29 19:39 UTC, picklelo approved these changes
awesome

2024-01-29 19:43 UTC, merged