many small changes from going over all props
reflex-dev/reflex pull request #2532
Opened 2024-02-06 01:53 UTC by tgberkeley

### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2024-02-06 19:55 UTC, masenf requested changes

2024-02-06 19:55 UTC, masenf commented on reflex/components/radix/themes/components/alertdialog.py
> +    size: Var[Literal["1", "2", "3", "4"]]
```suggestion
    size: Var[LiteralContentSize]
```

Does that not work?

2024-02-06 19:55 UTC, masenf commented on reflex/components/radix/themes/components/dropdownmenu.py
> +    # Button size "1" - "4"
```suggestion
    # Dropdown menu size "1" - "2"
```

2024-02-06 19:55 UTC, masenf commented on reflex/components/radix/themes/components/dropdownmenu.py
> +    high_contrast: Var[bool]
```suggestion
    # Variant of dropdown menu: "solid" | "soft"
    variant: Var[Literal["solid", "soft"]]

    # Override theme color for dropdown menu
    color_scheme: Var[LiteralAccentColor]

    # Whether to render the dropdown menu with higher contrast color against background
    high_contrast: Var[bool]
```

2024-02-07 00:04 UTC, tgberkeley commented on reflex/components/radix/themes/components/alertdialog.py
> +    size: Var[Literal["1", "2", "3", "4"]]
changed

2024-02-07 00:04 UTC, tgberkeley commented on reflex/components/radix/themes/components/dropdownmenu.py
> +    # Button size "1" - "4"
changed

2024-02-07 00:05 UTC, tgberkeley commented on reflex/components/radix/themes/components/dropdownmenu.py
> +    high_contrast: Var[bool]
changed

2024-02-07 19:37 UTC, masenf requested changes
regen pyi and we can take it

2024-02-08 02:16 UTC, picklelo approved these changes

2024-02-08 02:16 UTC, merged