Fix SQLAlchemy list types
reflex-dev/reflex pull request #2668
Opened 2024-02-19 18:33 UTC by benedikt-bartscher

2024-02-19 18:44 UTC, masenf requested changes
a test case would be cool too, but not strictly necessary since most of this code is already untested.

2024-02-19 18:44 UTC, masenf commented on reflex/utils/types.py
> +                return list[class_]
```suggestion
                return List[class_]
```

I think we should use cap `List` to keep py3.8 and py3.9 compatibility, if that works.

2024-02-19 20:47 UTC, benedikt-bartscher commented
@masenf I wanted to add tests later, if I have a fully working bare sqlalchemy with reflex. There are still some rough edges, f.e. with serialization, recursive/self-referencing relations and AssociationProxys. But I am getting close, most Issues are fixed in my reflex builds.  
There's also #2355 which needs some love before reflex can really support bare sqlalchemy

2024-02-20 23:14 UTC, masenf approved these changes

2024-02-20 23:14 UTC, merged