Benchmark with app harness
reflex-dev/reflex pull request #2774
Opened 2024-03-04 15:26 UTC by ElijahAhianyo

### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2024-03-11 20:43 UTC, masenf requested changes
Replace "Test that background tasks work as expected." with the actual description.

2024-03-11 20:43 UTC, masenf commented on benchmarks/test_benchmark_compile_components.py
> +def AppWithHUndredComponentOnePage():
```suggestion
def AppWithHundredComponentOnePage():
```

2024-03-11 20:43 UTC, masenf commented on benchmarks/test_benchmark_compile_components.py
> +        return rx.center(rx.vstack(*render_component(10)))
```suggestion
        return rx.center(rx.vstack(*render_component(1000)))
```

1000 right?

2024-03-12 10:07 UTC, ElijahAhianyo commented
> Replace "Test that background tasks work as expected." with the actual description.

Fixed 😅

2024-03-13 20:55 UTC, masenf approved these changes

2024-03-13 22:59 UTC, merged