generate pyi files when building/publishing 3rd party component
reflex-dev/reflex pull request #2945
Opened 2024-03-27 20:01 UTC by Lendemor

2024-03-27 21:51 UTC, martinxu9 commented
will try to look at the PR, but it works great with the newly published `reflex-calendar` with pyi files.

2024-03-28 19:05 UTC, masenf requested changes

2024-03-28 19:05 UTC, masenf commented on reflex/utils/pyi_generator.py
> +    pass
```suggestion
except ImportError:
    black = None
```

then down below, instead of catching blanket Exception, check for `if black is not None`

2024-03-28 19:51 UTC, masenf approved these changes
i appreciate your dedication to test coverage 😅

2024-03-28 19:56 UTC, Lendemor commented
> i appreciate your dedication to test coverage 😅

yeah they are in need of attention 😛

2024-03-29 01:19 UTC, picklelo submitted a review, later dismissed
works well on my custom components

2024-03-29 16:54 UTC, masenf approved these changes
Good to merge without the macos runs

2024-03-29 16:54 UTC, merged