Logic for removing the 'None' property along with its corresponding test cases
reflex-dev/reflex pull request #2969
Opened 2024-03-30 08:35 UTC by AmanSal1

### All Submissions:

- [X] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [X] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

### New Feature Submission:

- [X] Does your submission pass the tests? 
- [X Have you linted your code locally prior to submission?

### Changes To Core Features:

- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [X] Have you written new tests for your core changes, as applicable?
- [X] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    Logic for removing the 'None' property 

    b. Describe your changes.
     This commit fixes the removal of none props while creating the components  with its corresponding test cases

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
     Fixes: #2932

2024-04-01 19:33 UTC, picklelo requested changes
Thanks, change looks good to me! We just need to update some of the older unit tests that raised errors on `None`, can merge once the tests are passing.

2024-04-02 05:18 UTC, AmanSal1 commented
@picklelo Okay so like I don't have to do anything right ? Additionally Can you assign me some more good first issue ?

2024-04-02 17:15 UTC, masenf approved these changes
@picklelo i updated from `main` and removed the bad test case so we pass unit tests. I think we're good to go here now.

2024-04-02 18:36 UTC, picklelo approved these changes

2024-04-02 18:37 UTC, merged