add color dalle code example
reflex-dev/reflex pull request #3108
Opened 2024-04-18 00:41 UTC by tgberkeley

### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2024-04-18 17:32 UTC, masenf reviewed
### Initial Impression

---------

should `openai_client = openai.OpenAI()` be included in the blue box?

------------

> Use self. to call state class variables

Suggest "Use self. to access state variables for the current session"

---------

> Use State. when referring to state class variables (do not use self.)

Suggest "Use State. to render state vars and reference evnet handlers"

------------

I think under the backend section we should add "Code runs directly on the server". And under the frontend section we should add "Code translated to React/JS runs in the user's browser"

2024-04-18 19:51 UTC, masenf requested changes

2024-04-18 19:51 UTC, masenf commented on README.md
> +<img src="docs/images/dalle_colored_code_example.png" alt="A frontend wrapper for DALL·E, shown in the process of generating an image." width="900" />
```suggestion
<img src="docs/images/dalle_colored_code_example.png" alt="Explaining the differences between backend and frontend parts of the DALL-E app." width="900" />
```

2024-04-20 00:53 UTC, picklelo approved these changes

2024-04-20 00:54 UTC, merged