Fixed unused kwargs in reflex.App
reflex-dev/reflex pull request #3170
Opened 2024-04-26 08:34 UTC by Snaipergelka

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

Fixed kwargs `sio` and `socket_app` are not used during reflex.App initialization

Closes #3081

2024-04-26 16:58 UTC, Lendemor approved these changes

2024-04-26 17:01 UTC, masenf requested changes
Thanks for the contribution and tracking down that mysterious bug!

I have a couple of suggestions to improve the patch. The team has been wondering if exposing the `sio` externally is a good idea (yes it was documented, via generated docs), or if we should just expose the parameters as configuration knobs, like cors_allowed_origins.

For now, I'm leaning toward allowing the user to supply their own AsyncServer object.

2024-04-27 06:14 UTC, Snaipergelka commented on reflex/app.py
> +            )
Thank you for feedback. I updated patch.

2024-04-27 06:22 UTC, Snaipergelka commented
Updated patch in [commit](https://github.com/reflex-dev/reflex/pull/3170/commits/fbb527056591284174dc56ca442d6b2aaed5a5d3). Made `socket_app` local variable (deleted from the `reflex.App` args) and added check for `async_mode=asgi` for custom `sio` in `reflex.App`.

2024-04-29 20:15 UTC, masenf approved these changes

2024-04-29 20:53 UTC, merged