Update Spanish README.md
reflex-dev/reflex pull request #3330
Opened 2024-05-17 18:48 UTC by boterop

Fixes #3314 

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ x Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Context
Update the `docs/es/README.md` to match the latest version of the main `README.md`

2024-05-17 23:32 UTC, Lendemor commented
Thanks for contribution.

We've just merged #3313 which slightly change the demo code, if you can adjust your PR to match we'll be able to merged it.

2024-05-17 23:32 UTC, Lendemor requested changes
Thanks for contribution.

We've just merged https://github.com/reflex-dev/reflex/pull/3313 which slightly change the demo code, if you can adjust your PR to match we'll be able to merged it.

2024-05-18 19:07 UTC, boterop commented
> Thanks for contribution.
> 
> We've just merged #3313 which slightly change the demo code, if you can adjust your PR to match we'll be able to merged it.

Done 🤘🏼

2024-05-21 21:51 UTC, picklelo approved these changes

2024-05-21 21:51 UTC, merged