Feat: Add Session storage to store data on client storage
reflex-dev/reflex pull request #3420
Opened 2024-06-03 07:18 UTC by TG199

### Type of change

- [ ] New feature (non-breaking change which adds functionality)

### Description of change
Implemented SessionStorage class for managing session-related data in sessionStorage, enhancing project functionality

2024-06-03 08:03 UTC, TG199 commented
Why are they failing 😥

2024-06-03 17:49 UTC, masenf commented on reflex/__init__.py
> +        "SessionStorage" "ComponentState",
```suggestion
        "SessionStorage", "ComponentState",
```
```suggestion
        "SessionStorage" "ComponentState",
```

2024-06-03 17:52 UTC, masenf requested changes
there should be more line diff in `state.js`, basically `hydrateClientStorage` and `applyClientStorageDelta` should be updated to handle the session storage cases as well

2024-06-03 17:52 UTC, masenf commented on reflex/state.py
> +        inst.timeout = timeout
how do these get handled on the frontend / where did they come from?

2024-06-07 05:38 UTC, masenf requested changes
how did you test this? I tried extending `integration/test_client_storage.py` to add some `SessionStorage` state vars and they didn't get saved, so something isn't quite working.

I'll push uo the tests that i wrote quickly so you can run them, but its not necessarily exhaustive.

2024-06-07 05:38 UTC, masenf commented on reflex/.templates/web/utils/state.js
> +  if (client_storage.sessionStorage && typeof window != "undefined") {
```suggestion
  if (client_storage.session_storage && typeof window != "undefined") {
```

I think the key is `session_storage`, here and in various places below,

2024-06-14 21:07 UTC, TG199 commented
Finally!

2024-06-14 21:20 UTC, masenf approved these changes
Looks good!

2024-06-17 20:07 UTC, picklelo approved these changes
Some minor docstring issues that we can fix in a follow up

2024-06-17 20:07 UTC, picklelo commented on .pre-commit-config.yaml
> +        entry: python3 scripts/make_pyi.py
do we need this change?

2024-06-17 20:07 UTC, picklelo commented on reflex/event.py
> +    """Set a value in the session storage on the frontend.
should be "clear all values", looks like we missed this in the local_storage also

2024-06-17 20:07 UTC, picklelo commented on reflex/event.py
> +    """Set a value in the session storage on the frontend.
Should be "remove a value"

2024-06-17 21:31 UTC, merged