use different registry when in china, fixes #3700
reflex-dev/reflex pull request #3702
Opened 2024-07-24 23:17 UTC by adhami3310

2024-07-24 23:40 UTC, adhami3310 commented
@reigadegr can you give this a try?

2024-07-25 00:05 UTC, Lendemor requested changes

2024-07-25 00:05 UTC, Lendemor commented on reflex/utils/prerequisites.py
> +    if _is_in_china() or True:
```suggestion
    if _is_in_china():
```

2024-07-25 00:12 UTC, Lendemor submitted a review, later dismissed

2024-07-25 16:27 UTC, masenf reviewed
i'm really hesitant to depend on some remote IP location service.

1. it's exposing our users to a third party every time they use reflex
2. at best it's a proxy for the information we actually want: whether the chinese npm mirror has a faster response time than the default mirror

I think this functionality should instead compare the response times of various mirrors and pick the one that is the fastest.

2024-07-25 16:27 UTC, masenf commented on reflex/utils/china.py
> +            print(f"Error: {data['message']}")
we should use `rx.utils.console.info` to log this, and maybe include some more context, like "Failed geo-location lookup for your IP address"

2024-07-25 16:27 UTC, masenf commented on reflex/utils/china.py
> +        response = requests.get(f"http://ip-api.com/json")
We should use `httpx` to make any requests.

According to `pyproject.toml` reflex does not directly depend on `requests`, so if it happens to be installed, then we're getting it as a transitive dependency and cannot rely on it being in the environment (for example, if the dependency that brings it in transitively switches to `httpx` or `urllib3` or something else)

2024-07-25 17:03 UTC, masenf reviewed
i definitely like this better, but determining the fastest mirror adds noticeable time now. does this only hit at init time?

2024-07-25 17:22 UTC, Lendemor commented
Maybe we should just check is the env var REFLEX_NPM_REGISTRY is set.
If it is, we use the value set in there, if not we keep using the default like now.

2024-07-25 17:23 UTC, adhami3310 commented
It only adds a delay when initializing the web directory (once per init).

2024-07-25 17:24 UTC, adhami3310 commented
> If it slow the process, maybe we could just check is an env var like REFLEX_NPM_REGISTRY is set. If it is, we use the value set in there, if not we keep using the default like now.

This could be a cool option but many might not find it and has to put up with worse experience without knowing how to fix it.

2024-07-27 00:24 UTC, Alek99 commented
@FHU-yezi Would you be interested in testing this?

2024-07-29 01:30 UTC, reigadegr commented
@[adhami3310](https://github.com/adhami3310) 
Sorry，I am not able to compile the Python source code of reflex into an executable file.Could you teach me how to compile it, or send me the compiled file for testing?
I found a  method, which is to use the command 
```cmd
taskkill /F /IM bun.exe
```
 to let reflex call npm for installation, which is quite fast. The reason is that the 
```cmd
bun install
```
 command is very slow for me.

2024-07-29 02:31 UTC, seewindcn commented
> @FHU-yezi Would you be interested in testing this?
> 
> Let's wait to merge until someone can properly test and compare.

I had test "r.cnpmjs.org" by hand create .web\bunfig.toml; 
yes, it improved the package download experience;

2024-08-12 10:06 UTC, picklelo approved these changes

2024-08-12 10:06 UTC, merged