Setting State Vars that are not defined should raise an error
reflex-dev/reflex pull request #4007
Opened 2024-09-26 08:40 UTC by ElijahAhianyo

### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2024-09-26 21:14 UTC, Lendemor requested changes

2024-09-26 21:14 UTC, Lendemor commented on reflex/state.py
> +            raise AttributeError(
I think we should raise a SetUndefinedStateVar error instead.

2024-10-03 14:20 UTC, Lendemor approved these changes

2024-10-03 16:53 UTC, picklelo commented on reflex/state.py
> +            and name not in self.vars
nit: we may want to put this check first since it's the most common. Then if they are doing things correctly, it will avoid the above two checks

2024-10-03 17:35 UTC, picklelo approved these changes

2024-10-03 17:35 UTC, merged