fix and test bug in config env loading
reflex-dev/reflex pull request #4205
Opened 2024-10-20 16:56 UTC by benedikt-bartscher

2024-10-21 19:01 UTC, masenf submitted a review, later dismissed
seems reasonable

2024-10-23 16:04 UTC, Lendemor requested changes

2024-10-23 16:04 UTC, Lendemor commented on reflex/testing.py
> +        os.environ["TELEMETRY_ENABLED"] = "true"
Why `"true"` ? We still want this to be disabled for tests.

2024-10-23 23:31 UTC, masenf approved these changes

2024-10-24 15:50 UTC, Lendemor approved these changes

2024-10-24 17:27 UTC, merged